create schema test_schema;

create table if not exists test_schema.entity_one
    (
        column_2 integer,
        column_3 timestamp(6),
        id       bigint generated by default as identity
        primary key,
        column_1 varchar(255)
    );
